[package]
name = "stellar"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "^4.11.0"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "stellar"
path = "src/main.rs"
doc = true
doctest = true
