[package]
name = "stellar"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "^4.11.0"
actix-cors = "^0.7.1"
actix-governor = "0.8"
cargo-watch = "^8.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "stellar"
path = "src/main.rs"
doc = true
doctest = true
