[package]
name = "stellar-api"
version = "0.1.0"
edition = "2021"

# TODO review dependencies
[dependencies]
actix-web = "4.11.0"
actix-cors = "0.7.1"
actix-governor = "0.8"
env_logger = "0.11.8"
dotenvy = "0.15"
log = "0.4.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
zip = "^4.3.0"
walkdir = "^2.5.0"
tempfile = "^3.20.0"
globset = "^0.4.16"
stellar-cli = "23.0.1"
stellar-scaffold-cli = "0.0.7"
libc = "0.2"

[[bin]]
name = "stellar-api"
path = "src/main.rs"
